

INSERT INTO JobListings
 (idJobListings, Title, Field, Company, City, State, Address, ZipCode, Info, Email, Salary)
VALUES 
(4616789, 'Supervisory Mechanical Engineer', 'Engineering', 'Boeing', 'San Diego', 'California', '92734 Dreamers Ave', '90210', 'Overseeing the design, development, installation, and maintenance of mechanical systems in a variety of industries', 'boeingrecruiting@boeing.com', '$80,000 - $100,000'), 
(344914, 'Network Engineer', 'Engineering', 'The City of Knoxville', 'Knoxville', 'Tennessee', '9384 Rocky Top BLVD ste C', '37919', 'Designing, implementing, and maintaining computer networks for an organization', 'thecityofknoxville@jobs.com', '$65,000 - $80,000'),
(7931864, 'Electrical Engineer - Entry Level', 'Engineering', 'General Electric', 'Des Moines', 'Iowa', '2562 Timberline Road', '50312', 'Responsible for assisting in the design development and implementation of electrical systems and equipment for a variety of industries', 'hiringmanager@ge.com', '$50,000 - $65,000'),
(461934, 'Nuclear Engineer - Mid Level', 'Engineering', 'Duke Energy', 'Stamford', 'Connecticut', '789 Main Street', '06901', 'Responsible for designing, developing and maintaining nuclear power plants and their associated systems and components', 'dukeenergyjobs@dukeenergy.com', '$100,000+'),
(6297418, 'Automotive Sales Consultant', 'Sales', 'CarMax', 'Burlington', 'Vermont', '532 Maple Avenue', '05401', 'An Automotive Sales Consultant is responsible for selling cars, trucks, and other vehicles to customers', 'jobsatcarmax@carmax.com', '$35,000 - $50,000'),
(4619833, 'General Sales Manager', 'Sales', 'Grainger', 'Portland', 'Oregon', '5678 Main Street', '97205', 'Manage a team of sales professionals and work to develop and implement sales strategies to achieve the company\'s goals and objectives', 'graingertalentscout@jobhunting.com', '$100,000+'),
(4618721, 'Used Truck Sales Representative', 'Sales', 'Ryder', 'Kansas City', 'Missouri', '7805 Big Oak Circle', '64119', 'A Used Truck Sales Representative is responsible for selling pre-owned commercial trucks to businesses and individuals', 'hiringteam@ryder.com', '$35,000 - $50,000'),
(1394988, 'Entry Level Solar Sales Representative', 'Sales', 'SunPower', 'Miami', 'Florida', '9012 Oak Avenue', '33130', 'An Entry Level Solar Sales Representative is responsible for selling solar panel systems and related products and services to residential and commercial customers', 'sunpowerjobs@hireme.com', '$65,000 - $80,000'),
(1354962, 'Finance Director', 'Finance', 'State Farm', 'Atlanta', 'Georgia', '1234 Elm Street', '30303', 'A Finance Director is responsible for overseeing the financial operations of an organization including accounting, budgeting, forecasting, and financial reporting', 'statefarmjobpostings@statefarm.com', '$80,000 - $100,000'),
(7843957, 'Financial Analyst', 'Finance', 'ExxonMobil', 'Minneapolis', 'Minnesota', '4153 Cherry Blossom Lane', '55406', 'A Financial Analyst is responsible for analyzing financial data and providing insights and recommendations to help organizations make informed business decisions', 'financejobs@joblooker.com', '$65,000 - $80,000'),
(6791346, 'Financial Compliance Manager', 'Finance', 'IRS', 'Pittsfield', 'Massachusetts', '1243 North Street', '01201', 'A Financial Compliance Manager is responsible for ensuring that an organization adheres to all applicable laws, regulations, and internal policies related to financial reporting and compliance', 'irsjobboard@govjobs.com', '$100,000+'),
(3468411, 'Deposit Support Specialist', 'Finance', 'Wells Fargo', 'Las Vegas', 'Nevada', '7890 Pine Boulevard', '89109', 'A Deposit Support Specialist is responsible for providing customer support to ensure accurate and timely processing of deposits', 'wellsfargoemployment@wf.com', '$35,000 - $50,000'),
(3146477, 'Senior Software Engineer', 'Computer and Information Technology', 'Cerner', 'Chicago', 'Illinois', '11715 Prairie Avenue', '60646', 'A Senior Software Engineer is responsible for designing, developing and maintaining software applications and systems', 'cerneremployment@cerner.com', '$100,000+'),
(3149632, 'Computer Support Technician', 'Computer and Information Technology', 'IBM', 'Seattle', 'Washington', '1234 North Street', '98109', 'A Computer Support Technician is responsible for providing technical support and assistance to computer users within an organization', 'jobsatibm@ibm.com', '$50,000 - $65,000'),
(9432561, 'Machine Learning Engineer', 'Computer and Information Technology', 'Google', 'Portland', 'Maine', '45 Chestnut Street', '04101', 'A Machine Learning Engineer is responsible for developing and implementing machine learning models to solve complex problems and improve business outcomes', 'googletalentscout@googlejobs.com', '$100,000+'),
(3479337, 'Desktop Support Technician', 'Computer and Information Technology', 'Best Buy', 'New York', 'New York', '786 Fifth Avenue', '10019', 'A Desktop Support Technician is responsible for providing technical support to end-users for hardware and software issues related to desktops, laptops, and other computing devices', 'bestbuyjobs@bestbuy.com', '$50,000 - $65,000'),
(9843487, 'Community Health Worker', 'Healthcare', 'Medicaid Midwestern', 'Albuquerque', 'New Mexico', '5678 Main Avenue', '87106', 'A Community Health Worker is responsible for providing health education, outreach, and support to individuals and families in a specific community', 'healthcarejobpostings@jobs.com', '$35,000 - $50,000'),
(4873419, 'Clinic Medical Assistant', 'Healthcare', 'Alegiant Urgent Care', 'Helena', 'Montana', '3456 Pine Road', '59601', 'A Clinic Medical Assistant provides support to physicians, nurses, and other healthcare professionals in a clinical setting', 'alegianturgentcare@aucjobs.com', '$35,000 - $50,000'),
(6794563, 'Physical Therapist', 'Healthcare', 'Denver Physical Therapy', 'Denver', 'Colorado', '3456 Elm Street', '80202', 'A Physical Therapist (PT) is a licensed healthcare professional who evaluates and treats patients with physical impairments, injuries, or disabilities', 'dptjobs@dpt.com', '$80,000 - $100,000'),
(6497187, 'Psychiatric Nurse Practitioner', 'Healthcare', 'North Charleston Correctional Facility', 'Charleston', 'South Carolina', '5678 Main Street', '29401', 'A Psychiatric Nurse Practitioner (PNP) is a licensed healthcare professional who specializes in the diagnosis, treatment, and management of mental health disorders', 'nccfjoblistings@nccf.com', '$100,000+');
